In [1]:

import numpy as np
from scipy import misc
from PIL import Image
from sklearn.ensemble import RandomForestClassifier

im = Image.open('monalisa.jpg')
data = np.asarray( im, dtype="int32" )


In [12]:
#Selecting random pixels as input data for random forest regressor
import random
m,n = data.shape[:2]
output = []
input = []
for i in range(5000):
    y = random.randint(0,m-1)
    x = random.randint(0,n-1)
    input.append([y,x])
    output.append(data[y,x])
output = np.array(output) 
input = np.array(input)

In [3]:
data.shape

(900, 604, 3)

In [13]:
#training the random forest regressor
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(n_estimators=100)
clf = clf.fit(input, output)

In [14]:
clf


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [15]:
clf.predict([19,200])

array([[  98.07,  117.6 ,   73.01]])

In [16]:
data[19,200]

array([107, 109,  59], dtype=int32)

In [17]:
allPixels = [[y, x] for y in range(m) for x in range(n)]


In [18]:
#res array is now the approximation of the input image obtained by performing regression through random forests
res = clf.predict(allPixels)

array([[ 61.14,  96.47,  72.36],
       [ 61.14,  96.47,  72.36],
       [ 61.14,  96.47,  72.36],
       ..., 
       [ 21.56,  11.72,  37.34],
       [ 21.56,  11.72,  37.34],
       [ 21.56,  11.72,  37.34]])

In [20]:
#images can be checked in result folder
img2 = res.reshape(900,604,3)
from scipy.misc import toimage
toimage(img2).show()
#

In [ ]:
z

In [ ]:
## Decision tree outputs - Experiments with different no. of trees and depths. Check results folder###

In [27]:
clf2 = RandomForestRegressor(n_estimators=1,max_depth=1)
clf2 = clf2.fit(input, output)



In [28]:
res2 = clf2.predict(allPixels)

In [29]:
img3 = res2.reshape(900,604,3)
from scipy.misc import toimage
toimage(img3).show()

In [35]:
clf2 = RandomForestRegressor(n_estimators=1,max_depth=15)
clf2 = clf2.fit(input, output)

res2 = clf2.predict(allPixels)
img3 = res2.reshape(900,604,3)
from scipy.misc import toimage
toimage(img3).show()

In [40]:

clf2 = RandomForestRegressor(n_estimators=100,max_depth=7)
clf2 = clf2.fit(input, output)

res2 = clf2.predict(allPixels)
img3 = res2.reshape(900,604,3)
from scipy.misc import toimage
toimage(img3).show()

In [46]:
##Performing regression using K Nearest neighbors (with one neighbor only)
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=1)
neigh = neigh.fit(input, output) 

In [47]:
res2 = neigh.predict(allPixels)
img3 = res2.reshape(900,604,3)
from scipy.misc import toimage
toimage(img3).show()